name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "lakhsmycastro336@gmail.com"
          git config --global user.name "LaksCastro"
          git remote set-url origin https://${{ password }}@github.com/LaksCastro/minimal-ts-calculator>.git
          npm run pre-deploy
          npm run deploy
